<?php

/**
 * Script pour exécuter les migrations manquantes pour tous les hôpitaux
 */

require __DIR__ . '/../vendor/autoload.php';

$app = require_once __DIR__ . '/../bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Core\Models\Hospital;
use App\Core\Services\TenantConnectionService;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\DB;

echo "╔══════════════════════════════════════════════════════════════╗\n";
echo "║  Exécution des migrations manquantes                          ║\n";
echo "╚══════════════════════════════════════════════════════════════╝\n\n";

$hospitals = Hospital::whereIn('status', ['active', 'provisioning'])->get();

if ($hospitals->isEmpty()) {
    echo "❌ Aucun hôpital actif trouvé.\n";
    exit(1);
}

$tenantService = app(TenantConnectionService::class);

// Liste des modules avec leurs migrations
$modulesToMigrate = [
    'Absence' => [
        '2022_05_12_085232_create_missions_table.php',
        '2022_05_12_090158_create_type_vacations_table.php',
        '2022_05_12_090159_create_vacations_table.php',
        '2022_05_12_090319_create_om_autogenerateds_table.php',
        '2022_05_13_100355_create_mission_participants_table.php',
        '2023_07_24_112100_create_absents_table.php',
    ],
    'Movment' => [
        '2023_10_18_052043_create_service_movments_table.php',
        '2023_11_01_151016_create_antecedents_table.php',
        '2023_11_01_151052_create_livestyles_table.php',
        '2023_11_01_151128_create_allergies_table.php',
        '2023_11_01_152857_create_measurements_table.php',
        '2023_11_13_211221_create_patient_movement_details_table.php',
        '2023_11_13_213458_create_medical_files_table.php',
    ],
    'Hospitalization' => [
        '2023_11_26_195030_bed_patients.php',
        '2023_12_06_092452_room_options.php',
    ],
];

foreach ($hospitals as $hospital) {
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n";
    echo "🏥 Hôpital : {$hospital->name} (ID: {$hospital->id})\n";
    echo "   - Base de données : {$hospital->database_name}\n\n";
    
    try {
        $tenantService->connect($hospital);
        $tenantConnection = $tenantService->getCurrentConnection();
        
        // Vérifier quelles migrations ont été exécutées
        $executedMigrations = $tenantConnection->table('migrations')
            ->pluck('migration')
            ->toArray();
        
        echo "   📋 Migrations exécutées : " . count($executedMigrations) . "\n\n";
        
        // Exécuter les migrations manquantes par module
        foreach ($modulesToMigrate as $moduleName => $migrations) {
            echo "   📦 Module : {$moduleName}\n";
            
            foreach ($migrations as $migrationFile) {
                $migrationName = str_replace('.php', '', $migrationFile);
                
                // Vérifier si la migration a été exécutée
                if (in_array($migrationName, $executedMigrations)) {
                    echo "      ✅ {$migrationName} (déjà exécutée)\n";
                    continue;
                }
                
                // Exécuter la migration spécifique
                try {
                    Artisan::call('migrate', [
                        '--database' => 'tenant',
                        '--path' => "Modules/{$moduleName}/Database/Migrations/{$migrationFile}",
                        '--force' => true,
                    ]);
                    echo "      ✅ {$migrationName} (exécutée)\n";
                } catch (\Exception $e) {
                    // Ignorer les erreurs de contraintes vers hospitals (normal)
                    if (strpos($e->getMessage(), 'hospitals') !== false || 
                        strpos($e->getMessage(), 'hospital_id') !== false) {
                        echo "      ⚠️  {$migrationName} (contrainte hospitals ignorée)\n";
                    } else {
                        echo "      ❌ {$migrationName} : {$e->getMessage()}\n";
                    }
                }
            }
        }
        
        // Vérifier hospital_settings (peut être dans Administration)
        if (!in_array('2025_01_15_100012_create_hospital_settings_table', $executedMigrations)) {
            echo "   📦 Table hospital_settings\n";
            try {
                // Vérifier si la table existe déjà
                if (!$tenantConnection->getSchemaBuilder()->hasTable('hospital_settings')) {
                    // Créer la table manuellement si nécessaire
                    $tenantConnection->statement("
                        CREATE TABLE IF NOT EXISTS `hospital_settings` (
                            `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                            `key` varchar(255) NOT NULL,
                            `value` text,
                            `type` varchar(50) DEFAULT 'string',
                            `group` varchar(100) DEFAULT NULL,
                            `description` text,
                            `is_public` tinyint(1) DEFAULT 0,
                            `created_at` timestamp NULL DEFAULT NULL,
                            `updated_at` timestamp NULL DEFAULT NULL,
                            PRIMARY KEY (`id`),
                            UNIQUE KEY `hospital_settings_key_unique` (`key`)
                        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                    ");
                    echo "      ✅ Table hospital_settings créée\n";
                } else {
                    echo "      ✅ Table hospital_settings existe déjà\n";
                }
            } catch (\Exception $e) {
                echo "      ⚠️  hospital_settings : {$e->getMessage()}\n";
            }
        }
        
        // Vérifier telescope (peut être optionnel)
        $telescopeTables = ['telescope_entries', 'telescope_entries_tags', 'telescope_monitoring'];
        foreach ($telescopeTables as $table) {
            if (!$tenantConnection->getSchemaBuilder()->hasTable($table)) {
                echo "   ℹ️  Table {$table} n'existe pas (Telescope - optionnel)\n";
            }
        }
        
        // Compter les tables après
        $tablesAfter = $tenantConnection->select("
            SELECT COUNT(*) as count
            FROM INFORMATION_SCHEMA.TABLES
            WHERE TABLE_SCHEMA = ?
            AND TABLE_TYPE = 'BASE TABLE'
        ", [$hospital->database_name]);
        
        $tableCount = $tablesAfter[0]->count ?? 0;
        echo "\n   📊 Nombre de tables après : {$tableCount}\n";
        
    } catch (\Exception $e) {
        echo "   ❌ Erreur : {$e->getMessage()}\n";
    }
    
    echo "\n";
}

echo "╔══════════════════════════════════════════════════════════════╗\n";
echo "║                    TERMINÉ                                   ║\n";
echo "╚══════════════════════════════════════════════════════════════╝\n\n";
